@startuml
left to right direction
actor Пользователь

rectangle "MovieMate Bot" {
    usecase "Регистрация и авторизация" as UC1
    usecase "Настройка предпочтений" as UC2
    usecase "Поиск фильма по названию" as UC3
    usecase "Подборка фильмов по предпочтениям" as UC4
    usecase "Просмотр случайного фильма" as UC5
    usecase "Добавление фильма в избранное" as UC6
    usecase "Просмотр профиля" as UC7
}

Пользователь --> UC2
Пользователь --> UC3
Пользователь --> UC4
Пользователь --> UC5
Пользователь --> UC7

UC2 --> UC1 : <<include>>
UC3 --> UC1 : <<include>>
UC4 --> UC1 : <<include>>
UC5 --> UC1 : <<include>>
UC7 --> UC1 : <<include>>

UC4 --> UC6 : <<extend>>
UC5 --> UC6 : <<extend>>
@enduml
